### PR TITLE
Issue #33: Add vlucas/phpdotenv for local LAMP stack users.

### PR DESCRIPTION
**Pull request by vever001**
### Description
See https://github.com/openeuropa/drupal-site-template/issues/33

### CODE REVIEW

**Comment by vever001** [comment]
@voidtek Could you have a look at this PR please?
thx

**Comment by brummbar** [comment]
Hello @vever001 , we will always only support installations through Docker.

**Comment by vever001** [comment]
This is truly sad to hear.
I understand docker can save some discussions/issues with environment setup but for people who know what they are doing this is a good addition and has minimal impact.

For those interested I created a fork here https://github.com/vever001/drupal-site-template that contains this PR and https://github.com/openeuropa/drupal-site-template/pull/37 as well as some other minor additions.
I will keep maintaining the fork and merge upstream changes, unless otherwise stated on the project page.

**Comment by gervasek** [comment]
> Hello @vever001 , we will always only support installations through Docker.
Why? What is the problem to support lamp? The work is already done in this PR...

**Comment by brummbar** [comment]
It was a technical decision of OpenEuropa. All OpenEuropa components are developed using Docker containers to mimic the IT infrastructure where they will be deployed (see [here](https://github.com/openeuropa/documentation/blob/master/docs/starting/tooling.md#using-docker-compose)).
By using Docker, we cut down the "doesn't work on my machine" problems and the setup time for developers to start working/using components.
Components can of course be used without Docker, but we don't give support nor add functionalities to support that approach.

**Pull request closed without merging**
